insert into books (book_id, title, publish_date) values (1, 'Finding Normal', '10/10/2018');
insert into books (book_id, title, publish_date) values (2, 'On My Way (Elle s''en va)', '24/03/2018');
insert into books (book_id, title, publish_date) values (3, 'X2: X-Men United', '05/01/2019');
insert into books (book_id, title, publish_date) values (4, 'Sea Wife', '05/03/2018');
insert into books (book_id, title, publish_date) values (5, 'Guardians of the Galaxy', '22/06/2017');
insert into books (book_id, title, publish_date) values (6, 'Number Two (Numéro deux)', '31/07/2017');
insert into books (book_id, title, publish_date) values (7, 'Baby Boy', '17/01/2019');
insert into books (book_id, title, publish_date) values (8, 'Day of the Triffids, The', '05/03/2018');
insert into books (book_id, title, publish_date) values (9, 'Marvellous', '19/10/2018');
insert into books (book_id, title, publish_date) values (10, 'Don''t Deliver Us from Evil (Mais ne nous délivrez pas du mal)', '20/06/2017');
insert into books (book_id, title, publish_date) values (11, 'Field of Dreams', '31/01/2018');
insert into books (book_id, title, publish_date) values (12, 'Will Penny', '03/10/2018');
insert into books (book_id, title, publish_date) values (13, '55 Days at Peking', '11/05/2018');
insert into books (book_id, title, publish_date) values (14, 'Love the Beast', '10/11/2018');
insert into books (book_id, title, publish_date) values (15, 'Sweet Bunch (Glykia symmoria)', '01/02/2019');
insert into books (book_id, title, publish_date) values (16, 'Love Guru, The', '20/11/2017');
insert into books (book_id, title, publish_date) values (17, 'Tyler Perry''s Why Did I Get Married?', '26/06/2018');
insert into books (book_id, title, publish_date) values (18, 'Dreamlife of Angels, The (Vie rêvée des anges, La)', '08/02/2019');
insert into books (book_id, title, publish_date) values (19, 'Expert, The', '01/12/2017');
insert into books (book_id, title, publish_date) values (20, 'Shooting Gallery', '23/03/2018');
