insert into collections (col_id, name) values (1, 'Blytt''s Calcareous Moss');
insert into collections (col_id, name) values (2, 'Pleatleaf Knotweed');
insert into collections (col_id, name) values (3, 'Snake Canyon Milkvetch');
insert into collections (col_id, name) values (4, 'Featherleaf Desertpeony');
insert into collections (col_id, name) values (5, 'Aster');
insert into collections (col_id, name) values (6, 'Fringed Twinevine');
insert into collections (col_id, name) values (7, 'Wavyleaf Silktassel');
insert into collections (col_id, name) values (8, 'San Luis Obispo Sedge');
insert into collections (col_id, name) values (9, 'Oblique Maidenhair');
insert into collections (col_id, name) values (10, 'Greenland Brachythecium Moss');
insert into collections (col_id, name) values (11, 'Olympic Dichodontium Moss');
insert into collections (col_id, name) values (12, 'Mercurialis');
insert into collections (col_id, name) values (13, 'Florida Milkweed');
insert into collections (col_id, name) values (14, 'Ragged Nettlespurge');
insert into collections (col_id, name) values (15, 'Trichothelium Lichen');
insert into collections (col_id, name) values (16, 'Carolina Springbeauty');
insert into collections (col_id, name) values (17, 'Low Loosestrife');
insert into collections (col_id, name) values (18, 'Platte River Cinquefoil');
insert into collections (col_id, name) values (19, 'Howell''s Alkaligrass');
insert into collections (col_id, name) values (20, 'Lakeshore Panicgrass');
